# Generated by Django 4.2.1 on 2023-05-25 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createBase', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typeselection',
            options={},
        ),
        migrations.AlterModelManagers(
            name='typeselection',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='typeselection',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='typeselection',
            name='email',
        ),
        migrations.RemoveField(
            model_name='typeselection',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='typeselection',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='typeselection',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='typeselection',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='typeselection',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='typeselection',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='typeselection',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='typeselection',
            name='password',
        ),
        migrations.RemoveField(
            model_name='typeselection',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='typeselection',
            name='username',
        ),
    ]
