# Generated by Django 4.2.1 on 2023-05-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('name_product', models.CharField(max_length=500)),
                ('measure', models.CharField(max_length=50)),
                ('price', models.FloatField()),
            ],
        ),
    ]
