# Generated by Django 4.2.1 on 2023-05-24 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='base',
            old_name='measure',
            new_name='Ед_измерения',
        ),
        migrations.RenameField(
            model_name='base',
            old_name='category',
            new_name='Категория',
        ),
        migrations.RenameField(
            model_name='base',
            old_name='name_product',
            new_name='Название_продукта',
        ),
        migrations.RenameField(
            model_name='base',
            old_name='price',
            new_name='Цена',
        ),
    ]
