# Generated by Django 4.2.1 on 2023-05-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_base_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
